### ISSUE TITLE
Example using AoT compilation with ngc 

### ISSUE THREAD

**Issue by sumigoma** [AngularClass/angular-seed#11]
Not sure if it makes sense to have two different build configurations and bootstrap.ts files, but it would be nice to have an example of the setup for the new Ahead-of-Time compilation in RC5.

**Comment by gdi2290** [comment]
ya, I can add it. AOT has some restrictions but I did get it working outside of webpack

**Comment by GabrielDelepine** [comment]
Hi @gdi2290,

Any news on this ? 
I'am following [this angular compiler-cli issue #8759](https://github.com/angular/angular/issues/8759) and some endpoints seams missing to make it work properly with webpack.

**Comment by GabrielDelepine** [comment]
Sorry to be a little bit of topic, I just wanted to mention this repo : https://github.com/blacksonic/angular2-aot-webpack
