### ISSUE TITLE
help/doc: Global and component specific SASS support

### ISSUE THREAD

**Issue by mmrath** [AngularClass/angular-seed#24]
I have done the first step of `npm install node-sass postcss-loader sass-loader --save-dev`
Any pointers to get the global and component specific scss working?

**Comment by AurelieV** [comment]
For my personnal project, this is what I have done
* Add this to webpack loader `{ test: /\.scss/,  loaders: ['raw-loader','sass-loader']}`
* In each component, add styles: [require("my_path.scss")]

**Comment by gdi2290** [comment]
can someone add directions/how-to in the readme?
