### ISSUE TITLE
Cannot read property 'js' of undefined     at getDllAssets

### ISSUE THREAD

**Issue by BeanoKing** [AngularClass/angular-seed#28]
I can't get a proper build.  The Dist directory seems to be building correctly

**Comment by gassios** [comment]
in webpack.config.ts
app.get('/dll/*', (req, res) => {
          var files = req.path.split('/');
          var chunk = files[files.length -1].replace('.js', '');
          if(chunk.split('.').length<2)
            res.sendFile(root('dist/dll/'+ getDllAssets(chunk)));
          else
            res.sendFile(root('dist/dll/'+chunk));  
      });

dll directory contains files other than '.js' such as '.map' therefore getdllAssets chokes because webpack-assets.json does not contain those files in it's index.

**Comment by jschlemm** [comment]
^I had to change it to 
`app.get('/dll/*', (req, res) => {
var files = req.path.split('/');
var chunk = files[files.length -1].replace('.js', '');
if(chunk.split('.').length<2)
res.sendFile(root('dist/dll/'+ getDllAssets(chunk)));
else
res.sendFile(root('dist/dll/'+chunk));

});`

note the addition of the asterisk

**Comment by gdi2290** [comment]
@jschlemm can you make a pull-request?

**Comment by jschlemm** [comment]
PR created #29

**Comment by shlomiassaf** [comment]
experienced this issue today with most recent commit.
when running `npm run start` I get the above exception.

Trying to compile the DLL (`npm run dll`) result in this exception:
```
Template cannot be applied as TemplateArgument: HarmonyImportDependency
```

Which leads to this webpack issue: webpack/webpack#2644

Still not solved.

The workaround is to remove the DedupePlugin
