### ISSUE TITLE
Types of property resolve are imcompatible

### ISSUE THREAD

**Issue by magnattic** [AngularClass/angular-seed#37]
> Windows 7 (x64)
> node v6.6.0
> npm  v3.10.3

I get the following error when running `npm install` and `npm start` on a brandnew checkout:

> $ npm start
> 
> > angular2-seed@0.0.0 start C:\Projects\Playground\angular2-seed
> > npm run server:dev
> 
> 
> > angular2-seed@0.0.0 server:dev C:\Projects\Playground\angular2-seed
> > webpack-dev-server --env.ENV development
> 
> 
> C:\Projects\Playground\angular2-seed\node_modules\ts-node\dist\index.js:160
>                     throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset));
>                     ^
> TSError: ⨯ Unable to compile TypeScript
> webpack.config.ts (119,7): Type '{ cache: boolean; devtool: string; entry: { main: any[]; }; output: { path: any; filename: string...' is not assignable to type 'WebpackConfig'.
>   Types of property 'resolve' are incompatible.
>     Type '{ extensions: string[]; modules: any[]; }' is not assignable to type '{ unsafeCache?: boolean | string[]; root?: string; extensions?: string[]; }'.
>       Object literal may only specify known properties, and 'modules' does not exist in type '{ unsafeCache?: boolean | string[]; root?: string; extensions?: string[]; }'. (2322)

Any idea?

**Comment by JonathanVidmar** [comment]
Seems to be an issue with the lastest commit altering the webpack.config.
I solved it by removing the added line as specified in the commit.

**Comment by marcel-goedhart** [comment]
You need to add the following line to webpack.d.ts at line 27:

`modules?: Array<string>;`

Result should be:

```
resolve?: {
unsafeCache?: boolean | Array<string>;
root?: string;
extensions?: Array<string>;
modules?: Array<string>;
};
```

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular-seed/commit/48e8ac7b6cd5a3c3b4f9fe88bd88b346ce401331
