### ISSUE TITLE
This repo will be updated soon

### ISSUE THREAD

**Issue by gdi2290** [AngularClass/angular-seed#40]
I will be working on updating this repo this weekend.

## New Features

* [ ] Angular 4
* [ ] Pre-rendering
* [ ] Updated Folder Structure (new AngularClass best pratices)
* [ ] Updated Lazy Loading
* [ ] Updated Webpack Config Design
* [ ] Updated Support
* [ ] Faster Initial Boot
* [ ] New Update Cycle
* [ ] New Patterns  (new AngularClass best patterns)
* [ ] New Contributor System

**Comment by CatinhoCR** [comment]
I think the repo is not working atm, either that or im being a noob but I get errors when running npm install.
Error reads:
webpack-dev-server@2.4.5 requires a peer of webpack@^2.2.0 but none was installed.

I'm running on 
node v7.7.1, 
npm v4.1.2 and 
webpack  v2.5.1

Any ideas what might I be doing wrong??
